### ISSUE TITLE
Indenting is inconsistent

### ISSUE THREAD

**Issue by eduvik** [microsoftgraph/python3-connect-rest-sample#10]
Lots of tabs in the code, then places where there are 2 spaces for the indent. Convention (PEP8) is to use 4 spaces, and never tabs.

**Comment by jamescro** [comment]
Thanks for the feedback. Disregard the comment that I made to the issue you opened on the SDK. I had thought that you were commenting on this sample but now realize you were commenting on the sample code that is in the SDK's repo.

Please feel free to comment on any other areas where this sample could be more idiomatically Pythonic.

**Comment by jamescro** [comment]
I went through this with pylinter and updated the spacing in the files to be more consistent with idiomatic Python. Thanks for filing this issue.
