### ISSUE TITLE
Sample implementation of refresh token

### ISSUE THREAD

**Issue by truekonrads** [microsoftgraph/python3-connect-rest-sample#20]
Hello,

This is a feature request.  For completeness of example, this should have a refresh token which should be requested immediately after login and then subsequently use requests using the refresh tokens

**Comment by jasonjoh** [comment]
@truekonrads we are archiving this sample as it's no longer being maintained. We're replacing it with https://github.com/microsoftgraph/msgraph-training-pythondjangoapp
