### ISSUE TITLE
Can't access the app registration portal using school account

### ISSUE THREAD

**Issue by eduvik** [microsoftgraph/python3-connect-rest-sample#8]
When I try to follow the instructions to create an app at the registration portal (https://apps.dev.microsoft.com/), I click "register my app" it ask for a sign in, which I do, then it drops me in the microsoft account page(https://account.microsoft.com/?lang=en-US&refd=account.live.com&refp=landing), where I have no option to create an app. Is this a problem with the registration portal, or is the documentation on this project out of date?

**Comment by jamescro** [comment]
I can't reproduce this, with either my own corporate account or my live.com account. You should be able to use an MSA (live.com or outlook.com) as well as your work/school account (assuming you have one). Could you try that?

**Comment by eduvik** [comment]
OK, this is interesting. Works fine on a personal account (in Chrome). I tried my school account in Edge, and _that_ works fine, but when I try my school account in Chrome, it still fails.

**Comment by eduvik** [comment]
Looks like a browser cache or cookie issue; I tried in an incognito windows in chrome and it works now.
